### ISSUE TITLE
background task to get all data from apis

### ISSUE THREAD

**Issue by HealYouDown** [Concerned-Coyotes/summer-code-jam-2020#22]
We need a background task that runs every day (?) and queries the related information for all users from the apis.

- Weather (Specific for each user)
- Wikipedia Article of the day
- News
- ...

I did some googling and found [Django Background Tasks](https://django-background-tasks.readthedocs.io/en/latest/), maybe we could use that. Not sure if it is still compatible as the docs say up to 2.2.

Things like weather would also have to be queried and updated whenever a new user registers an account, so that we have data to display.

**Comment by maxrdu** [comment]
I am currently using django-background-tasks to create a task which fetches the news. However you need to run the tasks using the managment script. I (think) i fixed this by creating a thread on startup which uses `django.core.management.call_command` to run the tasks.
Weather could be queried once a day for a fixed set of locations, i.e. the world meteorological organization publishes wheater forecast for various location around the world once a [day](https://worldweather.wmo.int/en/dataguide.html).

**Comment by maxrdu** [comment]
It seems like my workaround is not working as it results in an error. Therefore we either have to run it from command line or setup something like celery or another task queue. However I have no experience with these
