### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by maxrdu** [Concerned-Coyotes/summer-code-jam-2020#3]
Currently I am not able to assing the issues to the project board, nor assign people, nor add labels to issues.
This means issues not opened by you will not show on the project board unless you add them @IgNoRaNt23.
This can be fixed by giving us the permissions in the seetings tab of the organization. More [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/setting-base-permissions-for-an-organization)

**Comment by IgNoRaNt23** [comment]
Switched general permissions to 'Write' for everyone. Does this solve your issue?

**Comment by maxrdu** [comment]
Yea this does thank you
