### ISSUE TITLE
Write a README.md with instructions on how to use our webapp

### ISSUE THREAD

**Issue by HealYouDown** [Concerned-Coyotes/summer-code-jam-2020#39]
We need a readme with some basic run instructions.

We could also add some thinking we did about our app and what we wanted to achieve.

This should be done at the end, once our app is finished.

**Comment by maxrdu** [comment]
In order to setup you need to run
```
pip install -r requirements.txt
python manage.py migrate
python manage.py setup_tasks
```

These instruction should be included in the readme

**Comment by HealYouDown** [comment]
Further information that should be included in the readme:

- What our project is and how we fit into the theme "the early internet"
- Include a list of features that we thought of but did not accomplish because of the time
- Explain what services we're using (APIs etc.)
- Explain the modules we use and their usage
- Include our sources for images
    - Background Image Link: https://unsplash.com/photos/IKbpXrInCJY
- A preview image (see below)
![preview image](https://user-images.githubusercontent.com/28159123/89733099-7519fe80-da53-11ea-9045-77c8ba906152.png)

**Comment by maxrdu** [comment]
The icons we are using are provided by [tablericons](https://tablericons.com/)
You should also mention that django-q is currently not working in Python 3.8 therefore I wrote a small command which manually runs the tasks but in other python versions the tasks should run every day
