### ISSUE TITLE
Get the weather forecast

### ISSUE THREAD

**Issue by IgNoRaNt23** [Concerned-Coyotes/summer-code-jam-2020#9]
Get weather forecast based on user location

**Comment by HealYouDown** [comment]
- [ ] A seperate app for weather
- [ ] A ProxyModel for the weather (To understand what a proxy model is, look location in [dashboard.models.py](https://github.com/Concerned-Coyotes/summer-code-jam-2020/blob/user-location/concerned-coyotes/earlyinternet/dashboard/models.py)). It should store `celsius`, `fahrenheit`, `sunset` and `sunrise`
- [ ] A function which takes `longitude `and `latitude `as arguments and returns the result from the api call stripped to just include what we want (the four fields above)
